project:
  type: website
  pre-render: copy_readme.R
  render: 
    - "**/index.md"

website:
  title: "Logbook"
  sidebar: 
    contents: auto

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    code-fold: show
    code-tools: 
      source: false
      toggle: true
