project:
  type: website
  output-dir: ../docs/

website:
  title: "Logbook"
  sidebar: 
    contents: 
      - index.qmd 
      # Can specify file order here. 
      # See https://quarto.org/docs/websites/website-navigation.html
      - section: Cleaning
        contents: "cleaning/**/*.md"
      - section: Analysis
        contents: "analysis/**/*.md"

format:
  html:
    theme: cosmo
    toc: true



