project:
  type: website
  output-dir: ../docs/

website:
  title: "Logbook"
  sidebar: 
    contents: 
      - index.qmd 
      - section: "Cleaning"
        contents:
          - cleaning/clean_census/index.qmd
          - cleaning/

format:
  html:
    theme: cosmo
    toc: true



