project:
  type: website
  pre-render: include/copy_readme.R
  render: 
    - "**/index.md"

website:
  title: "Logbook"
  sidebar: 
    style: "floating"
    contents: auto

format:
  html:
    theme: 
      - cosmo
      - include/cell-output.scss
    highlight-style: github
    toc: true
    toc-depth: 4
    toc-expand: 4
    include-after-body: 
      - include/toggle-code.html # Button to toggle code visibility
