project:
  type: website
  # pre-render: copy_readme.R
  render: 
    - "**/index.md"

website:
  title: "Logbook"
  sidebar: 
    contents: auto

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 4
    toc-expand: 4
    include-after-body: 
      - action_items.html # Toggle code visibility
