project:
  type: website
  pre-render: copy_readme.R
  render: 
    - "**/index.md"

website:
  title: "Logbook"
  sidebar: 
    style: "floating"
    contents: auto

format:
  html:
    theme: 
      - cosmo
      - cell-output.scss
    toc: true
    toc-depth: 4
    toc-expand: 4
    include-after-body: 
      - toggle-code.html # Button to toggle code visibility
